workflows:
  flet-android-build:
    name: Flet Android Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      groups:
        - python
    scripts:
      - name: Setup Python, Flet and Build APK
        script: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install flet==0.26.0
          flet build apk
    artifacts:
      - build/apk/*.apk
