workflows:
  flet-android-build:
    name: Flet Android Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      groups:
        - python
      vars:
        FLET_VERSION: "0.23.2"
    scripts:
      - name: Setup Python environment and Build APK
        script: |
          pip install flet==$FLET_VERSION
          flet build apk
    artifacts:
      - build/apk/*.apk
