name: Build Android App
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Buildozer Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev liblzma-dev lzma
          pip install buildozer cython

      - name: Build APK using Buildozer
        run: |
          if [ -f "main.py.py" ]; then mv main.py.py main.py; fi
          buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,tkintermapview,geopy,requests/g' buildozer.spec
          buildozer -v android debug
        env:
          PURGATORY: "true"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: taty-nawigacja
          path: bin/*.apk
