name: Build Flet APK
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java Jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet and Build
        run: |
          pip install flet==0.26.0
          # Ta linijka naprawia nazwę pliku, jeśli zapisał się jako main.py.py
          if [ -f "main.py.py" ]; then mv main.py.py main.py; fi
          flet build apk

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-android-app
          path: build/apk/*.apk
